### ISSUE TITLE
Documentation-repo brainstorming

### ISSUE THREAD

**Issue by khuynh2002** [SecurityLogMiner/log-collection-documentation#1]
This repo will serve to provide more insight on how to use our finalized tool, while also allowing for proper maintainability of feature implementations/changes that happen along the development way. 

Helpful things to document for team members:

- Any templates that could be reused for future documents
- Concept visualizations
- API references

Helpful things for users:

- Version changes
- FAQ page
- Tool features list and description
- Installation/Configuration guide 

Some of these are for future implementations. If there are any other ideas now or developed later, we can list them in this thread.

**Comment by endepointe** [comment]
readthedocs for user documentation (or something similar) would be helpful.

other than the readme, maybe the developer/maintainer documentation could go in readthedocs as well?
