### ISSUE TITLE
[Documentation] SDA Draft

### ISSUE THREAD

**Issue by Jicxer** [SecurityLogMiner/log-collection-documentation#15]
Started on the SDA draft:
Created a new branch on the documentation repository

https://github.com/SecurityLogMiner/log-collection-documentation/blob/draft-sda/SDA.md

Will work on it throughout tonight

**Comment by endepointe** [comment]
still working on sda draft. latest updates were to the security considerations section:

https://github.com/SecurityLogMiner/log-collection-documentation/tree/draft-sda
